[package]
name = "ria"
version = "0.1.5"
edition = "2021"

[dependencies]
file-format = "0.7"
glib = "0.15"
gstreamer = "0.18"
gstreamer-pbutils = "0.18"
musicbrainz_rs = "0.4"
once_cell = "1.16"
percent-encoding = "2.2"
sea-orm = { version = "0.10", features = ["sqlx-postgres", "runtime-tokio-rustls" ] }
sea-query = "0.27"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2.3"
