//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "audiotag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tid: i32,
    pub aid: i32,
    pub name: String,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::audio::Entity",
        from = "Column::Aid",
        to = "super::audio::Column::Aid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Audio,
}

impl Related<super::audio::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Audio.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
