//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "directory")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub directory_id: i32,
    pub created: DateTime,
    pub updated: DateTime,
    pub path: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artist_directory::Entity")]
    ArtistDirectory,
    #[sea_orm(has_many = "super::audio_directory::Entity")]
    AudioDirectory,
}

impl Related<super::artist_directory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistDirectory.def()
    }
}

impl Related<super::audio_directory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AudioDirectory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
