//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod prelude;

pub mod artist;
pub mod artist_area;
pub mod audio;
pub mod audio_artist;
pub mod audio_tag;
pub mod image;
pub mod musicbrainz_queue;
