//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

pub use super::artist::Entity as Artist;
pub use super::audio::Entity as Audio;
pub use super::audioartist::Entity as Audioartist;
pub use super::audiotag::Entity as Audiotag;
pub use super::image::Entity as Image;
