//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::artist::Entity as Artist;
pub use super::artist_area::Entity as ArtistArea;
pub use super::audio::Entity as Audio;
pub use super::audio_artist::Entity as AudioArtist;
pub use super::audio_tag::Entity as AudioTag;
pub use super::image::Entity as Image;
